version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  swagger:
    image: swaggerapi/swagger-ui
    depends_on:
      - web
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      API_URL: http://localhost:3000/api/api_docs
